[project]
dependencies = [
  "beautifulsoup4==4.12.3",
  "fire==0.7.0",
  "requests==2.32.3"
]
name = "parcel-tracker"
version = "0.0.0"

[project.optional-dependencies]
dev = [
  "coverage==7.6.10",
  "djlint==1.36.4",
  "mypy==1.14.1",
  "ruff==0.8.4",
  "ssort==0.14.0",
  "toml-sort==0.24.2"
]

[project.scripts]
parcel-tracker = "main:main"

[tool.setuptools]
py-modules = ["main"]
