[project]
dependencies = [
  "beautifulsoup4==4.12.3",
  "fire==0.7.0",
  "requests==2.32.3"
]
name = "parcel-tracker"
version = "0.0.0"

[project.optional-dependencies]
dev = [
  "coverage==7.6.4",
  "djlint==1.35.3",
  "mypy==1.13.0",
  "ruff==0.7.1",
  "ssort==0.13.0",
  "toml-sort==0.23.1"
]

[project.scripts]
parcel-tracker = "main:main"

[tool.setuptools]
py-modules = ["main"]
